config/routes.rb
Rails.application.routes.draw do
  get 'balance/index'
  post 'balance/index'
  resources :transfers, only:[:index, :create, :show, :new]
  resources :withdraws, only:[:index, :create, :show, :new]
  resources :deposits, only:[:index, :create, :show, :new]
  resources :accounts, except:[:index, :create, :show, :new]
  devise_for :users
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:"wellcome#index"
  get 'wellcome/index'
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :account, dependent: :destroy
  has_many :balances
  after_save :increment_balance
  validates :amount, :numericality => {:greater_than_or_equal_to => 1 }, presence:true
  def increment_balance
   BankOperations.increment(self.id, self.class.name, 0)
  end
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  before_action :set_deposit, only: [:show, :edit, :update, :destroy]

  # GET /deposits
  # GET /deposits.json
  def index
    @deposits = current_user.account.deposits
  end

  # GET /deposits/1
  # GET /deposits/1.json
  def show
  end

  # GET /deposits/new
  def new
    @deposit = Deposit.new
  end

  # GET /deposits/1/edit
  def edit
  end

  # POST /deposits
  # POST /deposits.json
  def create
    @deposit = current_user.account.deposits.new(deposit_params)

    respond_to do |format|
      if @deposit.save
        format.html { redirect_to @deposit, notice: 'Deposito efetuado com sucesso.' }
        format.json { render :show, status: :created, location: @deposit }
      else
        format.html { render :new }
        format.json { render json: @deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deposits/1
  # PATCH/PUT /deposits/1.json
  def update
    respond_to do |format|
      if @deposit.update(deposit_params)
        format.html { redirect_to @deposit, notice: 'Deposit was successfully updated.' }
        format.json { render :show, status: :ok, location: @deposit }
      else
        format.html { render :edit }
        format.json { render json: @deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deposits/1
  # DELETE /deposits/1.json
  def destroy
    @deposit.destroy
    respond_to do |format|
      format.html { redirect_to deposits_url, notice: 'Deposit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deposit
      @deposit = Deposit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def deposit_params
      params.require(:deposit).permit(:account_id, :amount)
    end
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/views/deposits/_form.html.erb
<%= form_for @deposit, :html => { :class => "form-horizontal deposit" } do |f| %>

  <% if @deposit.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@deposit.errors.count, "error") %> prohibited this deposit from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @deposit.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  
  <div class="form-group">
    <%= f.label :amount, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :amount, :class => 'form-control' %>
    </div>
    <%=f.error_span(:amount) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                deposits_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/deposits/edit.html.erb
<%- model_class = Deposit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/deposits/index.html.erb
<%- model_class = Deposit -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:account_id) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @deposits.each do |deposit| %>
      <tr>
        <td><%= link_to deposit.id, deposit_path(deposit) %></td>
        <td><%= deposit.account_id %></td>
        <td><%= Extenso.real_formatado(deposit.amount) %></td>
        <td><%=l deposit.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      deposit_path(deposit), :class => 'btn btn-default btn-xs' %>
          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_deposit_path,
            :class => 'btn btn-primary' %>

app/views/deposits/new.html.erb
<%- model_class = Deposit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', ' %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/deposits/show.html.erb
<%- model_class = Deposit -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= Extenso.real_formatado(@deposit.amount) %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              deposits_path, :class => 'btn btn-default'  %>