config/routes.rb
Rails.application.routes.draw do
  get 'balance/index'
  post 'balance/index'
  resources :transfers, only:[:index, :create, :show, :new]
  resources :withdraws, only:[:index, :create, :show, :new]
  resources :deposits, only:[:index, :create, :show, :new]
  resources :accounts, except:[:index, :create, :show, :new]
  devise_for :users
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:"wellcome#index"
  get 'wellcome/index'
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :account
  has_many :balances
  validates :amount, :numericality => { :greater_than_or_equal_to => 1 }, presence: true 
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]
  before_action :verify_transfer, only: [:create]

  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = current_user.account.transfers
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
  end

  # GET /transfers/new
  def new
    @transfer = Transfer.new
  end

  # GET /transfers/1/edit
  def edit
  end

  # POST /transfers
  # POST /transfers.json
  def create
    @transfer = current_user.account.transfers.new(transfer_params)
    respond_to do |format|
      if @transfer.save
        BankOperations.increment_decrement(@transfer.id, @transfer.account_to, @transfer.amount)
        format.html { redirect_to @transfer, notice: 'Transferência efetuada com sucesso.' }
        format.json { render :show, status: :created, location: @transfer }
      else
        format.html { render :new }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to @transfer, notice: 'Transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @transfer }
      else
        format.html { render :edit }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to transfers_url, notice: 'Transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def verify_transfer
      account_to = Account.find_by(id: transfer_params[:account_to])
      @transfer = current_user.account.transfers.new(transfer_params)
      last_balance = current_user.account.get_balance
      if @transfer.amount.to_f + BankOperations.get_tax(@transfer.amount)  > last_balance
        @transfer.errors.add(:message, "Saldo insuficiente")
        respond_to do |format|
          format.html { render :edit }
          format.json { render json: @transfer.errors, status: :unprocessable_entity}
        end
      elsif account_to.nil?
        @transfer.errors.add(:message, 'Conta não encontrada')
        respond_to do |format|
          format.html { render :edit }
          format.json { render json: @transfer.errors, status: :unprocessable_entity}
        end
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transfer_params
      params.require(:transfer).permit(:account_id, :amount, :account_to)
    end
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/transfers/_form.html.erb
<%= form_for @transfer, :html => { :class => "form-horizontal transfer" } do |f| %>

  <% if @transfer.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@transfer.errors.count, "error") %> prohibited this transfer from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @transfer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  
  <div class="form-group">
    <%= f.label :amount, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :amount, :class => 'form-control' %>
    </div>
    <%=f.error_span(:amount) %>
  </div>
  <div class="form-group">
    <%= f.label :account_to, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :account_to, :class => 'form-control' %>
    </div>
    <%=f.error_span(:account_to) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                transfers_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/transfers/edit.html.erb
<%- model_class = Transfer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/transfers/index.html.erb
<%- model_class = Transfer -%>
<div class="page-header">
  <h1><%=t ".title", :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:account_id) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:account_to) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @transfers.each do |transfer| %>
      <tr>
        <td><%= link_to transfer.id, transfer_path(transfer) %></td>
        <td><%= transfer.account_id %></td>
        <td><%= transfer.amount %></td>
        <td><%= transfer.account_to %></td>
        <td><%=l transfer.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      transfer_path(transfer), :class => 'btn btn-default btn-xs' %>
          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_transfer_path,
            :class => 'btn btn-primary' %>

app/views/transfers/new.html.erb
<%- model_class = Transfer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', '%{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/transfers/show.html.erb
<%- model_class = Transfer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:account_id) %>:</strong></dt>
  <dd><%= @transfer.account_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @transfer.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:account_to) %>:</strong></dt>
  <dd><%= @transfer.account_to %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              transfers_path, :class => 'btn btn-default'  %>