config/routes.rb
Rails.application.routes.draw do
  get 'balance/index'
  post 'balance/index'
  resources :transfers, only:[:index, :create, :show, :new]
  resources :withdraws, only:[:index, :create, :show, :new]
  resources :deposits, only:[:index, :create, :show, :new]
  resources :accounts, except:[:index, :create, :show, :new]
  devise_for :users
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:"wellcome#index"
  get 'wellcome/index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Banknobe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <% if user_signed_in? %>
      <%= nav_bar fixed: :top, responsive: true do %>
        <%= menu_group pull: :left do %>
          <%= menu_item t('activerecord.models.wellcome.one'), root_path %>
        <% end %>
        <%= menu_group pull: :left do %>
          <%= menu_item t('activerecord.models.deposit.others'), deposits_path %>
        <% end %>
        <%= menu_group pull: :left do %>
          <%= menu_item t('activerecord.models.withdraw.others'), withdraws_path %>
        <% end %>
        <%= menu_group pull: :left do %>
          <%= menu_item t('activerecord.models.transfer.others'), transfers_path %>
        <% end %>
        <%= menu_group pull: :left do %>
          <%= menu_item t('activerecord.models.balance.others'), balance_index_path %>
        <% end %>
        <%= menu_group pull: :right do %>
          <% if current_user %>
            <%= menu_item t('activerecord.models.wellcome.sign_out'), destroy_user_session_path %>
          <% else %>
            <%= form_for @user, url: session_path(:user), html => {class: "navbar-form pull-right"} do |f| -%>
              <p><%= f.text_field :email %></p>
              <p><%= f.password_field :password %></p>
              <p><%= f.submit t('activerecord.models.wellcome.sign_in') %></p>
            <% end -%>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>